apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::716482896146:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6CYMNOUZHERI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::716482896146:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T16:54:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1998"
  uid: 1f5d9ab1-851f-40b3-869e-148ed242eee3
